// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcia1.Data;

#nullable disable

namespace Parcia1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305082335_InicialDB")]
    partial class InicialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcia1.Models.Auditorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("RolUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolUsuarioId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Parcia1.Models.Destinatarios", b =>
                {
                    b.Property<int>("DestinatariosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinatariosId"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinatariosId");

                    b.ToTable("Destinatarios");
                });

            modelBuilder.Entity("Parcia1.Models.Envios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DestinatariosId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaquetesId")
                        .HasColumnType("int");

                    b.Property<int>("RolUsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinatariosId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PaquetesId");

                    b.HasIndex("RolUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Envio");
                });

            modelBuilder.Entity("Parcia1.Models.EstadosEnvio", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("EstadosEnvio");
                });

            modelBuilder.Entity("Parcia1.Models.Paquetes", b =>
                {
                    b.Property<int>("PaquetesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaquetesId"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<decimal>("peso")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PaquetesId");

                    b.HasIndex("EnvioId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Parcia1.Models.RolUsuario", b =>
                {
                    b.Property<int>("RolUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolUsuarioId"));

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolUsuarioId");

                    b.ToTable("RolUsuario");
                });

            modelBuilder.Entity("Parcia1.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RolUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolUsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Parcia1.Models.Auditorias", b =>
                {
                    b.HasOne("Parcia1.Models.RolUsuario", "RolUsuario")
                        .WithMany()
                        .HasForeignKey("RolUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolUsuario");
                });

            modelBuilder.Entity("Parcia1.Models.Envios", b =>
                {
                    b.HasOne("Parcia1.Models.Destinatarios", "Destinatarios")
                        .WithMany("Envio")
                        .HasForeignKey("DestinatariosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parcia1.Models.EstadosEnvio", "EstadosEnvio")
                        .WithMany("Envio")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcia1.Models.Paquetes", null)
                        .WithMany("Envio")
                        .HasForeignKey("PaquetesId");

                    b.HasOne("Parcia1.Models.RolUsuario", "RolUsuario")
                        .WithMany()
                        .HasForeignKey("RolUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parcia1.Models.Usuario", "Usuario")
                        .WithMany("Envio")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Destinatarios");

                    b.Navigation("EstadosEnvio");

                    b.Navigation("RolUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Parcia1.Models.Paquetes", b =>
                {
                    b.HasOne("Parcia1.Models.Envios", "Envios")
                        .WithMany()
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envios");
                });

            modelBuilder.Entity("Parcia1.Models.Usuario", b =>
                {
                    b.HasOne("Parcia1.Models.RolUsuario", "RolUsuario")
                        .WithMany()
                        .HasForeignKey("RolUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolUsuario");
                });

            modelBuilder.Entity("Parcia1.Models.Destinatarios", b =>
                {
                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Parcia1.Models.EstadosEnvio", b =>
                {
                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Parcia1.Models.Paquetes", b =>
                {
                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Parcia1.Models.Usuario", b =>
                {
                    b.Navigation("Envio");
                });
#pragma warning restore 612, 618
        }
    }
}
