// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcia1.Data;

#nullable disable

namespace Parcia1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcia1.Models.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Parcia1.Models.Destinatarios", b =>
                {
                    b.Property<int>("DestinatarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinatarioId"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinatarioId");

                    b.ToTable("Destinatarios");
                });

            modelBuilder.Entity("Parcia1.Models.Envios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<int>("DestinatariosId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaquetesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DestinatariosId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PaquetesId");

                    b.ToTable("Envio");
                });

            modelBuilder.Entity("Parcia1.Models.EstadosEnvio", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("EstadosEnvio");
                });

            modelBuilder.Entity("Parcia1.Models.Paquetes", b =>
                {
                    b.Property<int>("PaquetesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaquetesId"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<decimal>("peso")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PaquetesId");

                    b.HasIndex("EnvioId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Parcia1.Models.Envios", b =>
                {
                    b.HasOne("Parcia1.Models.Clientes", "Clientes")
                        .WithMany("Envio")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcia1.Models.Destinatarios", "Destinatarios")
                        .WithMany("Envio")
                        .HasForeignKey("DestinatariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcia1.Models.EstadosEnvio", "EstadosEnvio")
                        .WithMany("Envio")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcia1.Models.Paquetes", null)
                        .WithMany("Envio")
                        .HasForeignKey("PaquetesId");

                    b.Navigation("Clientes");

                    b.Navigation("Destinatarios");

                    b.Navigation("EstadosEnvio");
                });

            modelBuilder.Entity("Parcia1.Models.Paquetes", b =>
                {
                    b.HasOne("Parcia1.Models.Envios", "Envios")
                        .WithMany()
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envios");
                });

            modelBuilder.Entity("Parcia1.Models.Clientes", b =>
                {
                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Parcia1.Models.Destinatarios", b =>
                {
                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Parcia1.Models.EstadosEnvio", b =>
                {
                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Parcia1.Models.Paquetes", b =>
                {
                    b.Navigation("Envio");
                });
#pragma warning restore 612, 618
        }
    }
}
